[window]
opacity = 0.9
padding.x = 10
padding.y = 10

[font]

normal.family = "RobotoMono Nerd Font"
bold.family = "RobotoMono Nerd Font"
italic.family = "RobotoMono Nerd Font"
bold_italic.family = "RobotoMono Nerd Font"

size = 12

