#general.import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]

opacity = 0.97

padding.x = 10
padding.y = 10

[font]

normal.family = "RobotoMono Nerd Font"
bold.family = "RobotoMono Nerd Font"
italic.family = "RobotoMono Nerd Font"
bold_italic.family = "RobotoMono Nerd Font"

size = 12
