# The structure is based on `base16_default_dark` by Ray Gervais.  Most of
# the colors come from the so called Autumn theme, a color scheme inspired by
# the colors you can find in the autumn. Originally it was designed as a
# color scheme for the Komodo IDE and then ported to Vim by Kenneth Love
# and Chris Jones. Later, Yorick Peterse improved their work. See:
# <https://github.com/YorickPeterse/Autumn.vim>
# Jens Getreu ported and optimised the color theme for the Helix editor.
# Author: Jens Getreu <getreu at web.de>

#"ui.background" = { bg = "gruber_daker_bg" }
"ui.menu" = { fg = "gruber_darker_white", bg = "gruber_darker_black" }
"ui.menu.selected" = { fg = "gruber_darker_black", bg = "gruber_darker_gray" }
"ui.linenr" = { fg = "gruber_darker_gray", bg = "gruber_daker_bg" }
"ui.popup" = { bg = "gruber_darker_black" }
"ui.window" = { fg = "gruber_darker_gray", bg = "gruber_darker_black" }
"ui.linenr.selected" = { fg = "gruber_darker_white", bg = "gruber_daker_bg"}
"ui.selection" = { bg = "gruber_darker_gray" }
"comment" = { fg = "gruber_darker_brown", modifiers = ["italic"] }
"ui.cursorline" = { bg = "gruber_darker_gray" }
"ui.statusline" = { fg = "gruber_darker_white", bg = "gruber_darker_black" }
"ui.statusline.inactive" = { fg = 'gruber_darker_brown', bg = 'gruber_darker_black' }
"ui.statusline.insert" = {fg = "gruber_darker_black", bg = "gruber_darker_gray", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "gruber_darker_white", bg = "gruber_darker_black"}
"ui.statusline.select" = {fg = "gruber_darker_white", bg = "gruber_darker_black", modifiers = ["bold"]}
"ui.cursor" = { fg = "gruber_darker_gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "gruber_darker_white", modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "gruber_darker_black" }
"ui.cursorline.secondary" = { bg = "gruber_darker_black" }
"ui.text" = "gruber_darker_white"
"operator" = "gruber_darker_white"
"ui.text.focus" = "gruber_darker_white"
"variable" = "gruber_darker_white"
"constant.numeric" = "gruber_darker_quartz"
"constant" = "gruber_darker_white"
"attribute" = "gruber_darker_quartz"
"type" = { fg = "gruber_darker_quartz", modifiers = ["italic"] }
"ui.cursor.match" = { fg = "gruber_darker_white", modifiers = ["underlined"] }
"string"  = "my_green"
"variable.other.member" = "my_brown"
"constant.character.escape" = "gruber_darker_quartz"
"function" = "my_yellow1"
"constructor" = "my_yellow1"
"special" = "my_yellow1"
"keyword" = "gruber_yellow"
"label" = "gruber_yellow"
"namespace" = "gruber_darker_white"
"ui.help" = { fg = "gruber_darker_white", bg = "gruber_darker_black" }
"ui.virtual.whitespace" = { fg = "gruber_darker_gray" }
"ui.virtual.ruler" = { bg = "gruber_darker_black" }

"markup.heading" = "my_yellow1"
"markup.list" = "gruber_darker_white"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = {  modifiers = ["italic"] }
"markup.link.url" = "gruber_darker_quartz2"
"markup.link.text" = "gruber_darker_white"
"markup.quote" = "my_brown"
"markup.raw" = "my_green"

"diff.plus" = "my_green"
"diff.delta" = "gruber_darker_gray"
"diff.minus" = "gruber_red_error"

"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.error" = { underline = { style = "curl", color = "gruber_yellow" } }
"ui.gutter" = { bg = "gruber_daker_bg" }
"hint" = "gruber_darker_gray"
"debug" = "my_yellow2"
"info" = "gruber_darker_quartz"
"warning" = "gruber_darker_quartz2"
"error" = "gruber_red_error"

[palette]
# Default Background
gruber_daker_bg      = "#1c1c1c" 
# Cursorline, Ruler, Lighter Background (Used for status bars, line number and folding marks)
gruber_darker_black  = "#262626" 
# Comments, Invisibles, Line Highlighting
gruber_darker_brown  = "#cc8c3c"
# Dark Foreground (Used for status bars,Selection Background)
gruber_darker_gray   = "#626262"
# Default Foreground, Caret, Delimiters, Operators
# Light Foreground,Light Background (Not often used)
# Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# Classes, Markup Bold, Search Text Background
gruber_darker_white  = "#ffffff"
# Support, Regular Expressions, Escape Characters
gruber_darker_quartz = "#95a99f"
# URL
gruber_darker_quartz2 = "#afd7af"
# Strings, Inherited Class, Markup Code, Diff Inserted
my_green      = "#73c936"
# Memer variables, Quotes
my_brown      = "#96a6c8"
# Functions, Methods, Attribute IDs, Headings
my_yellow1    = "#87afd7"
# Debug, Info
my_yellow2    = "#ff5f5f"
# Keywords, Storage, Selector, Diff Changed
gruber_yellow = "#ffd700"
# Diagnostic Errors
gruber_red_error = "#ff5f5f" 

#GRUBER COLORS
# black = "#1c1c1c"
# lightblack = "#262626"
# darkgray = "#444444"
# gray = "#626262"
# white = "#e4e4e4"
# red = "#ff5f5f"
# green = "#87d75f"
# yellow = "#ffd700"
# blue = "#87afd7"
# magenta = "#afafd7"
# cyan = "#afd7af"
# brown = "#af875f"
