# The theme uses the gruvbox dark palette with hard contrast: github.com/morhetz/gruvbox
inherits = "gruvbox"

"diagnostic.error" = { underline = { color = "red0", style = "curl"} }

[palette]
bg0 = "#1d2021" # main background