theme = "dark_plus"

[editor]
color-modes = true
completion-trigger-len = 1
#line-number = "relative"
bufferline = "never"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = false

# command list here: https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
[keys.normal]
X = "extend_line_above"
# Delete to end of line from cursor
D = "kill_to_line_end"
# Buffer management
C-l = "goto_next_buffer"
C-h = "goto_previous_buffer"
C-b = "buffer_picker"
esc = [
  "collapse_selection", 
  "keep_primary_selection"
]
Y = [
  "select_mode", 
  "goto_line_end", 
  "yank_main_selection_to_clipboard", 
  "normal_mode", 
  "collapse_selection"
]
C-p = "file_picker"
# Move highlighted lines
C-j = [
  "extend_to_line_bounds", 
  "delete_selection", 
  "paste_after"
]
C-k = [
  "extend_to_line_bounds", 
  "delete_selection", 
  "move_line_up", 
  "paste_before"
]

[keys.normal.'space']
g = ":sh tmux split-window -v -l 70% -c '#{pane_current_path}' lazygit"
x = ":buffer-close"
c = ":theme catppuccin_mocha"
e = ":sh tmux_fs"
l = "goto_last_accessed_file"
# This keybind below is used by lf script
"." = [
  ":open fs_scratcher",
  "paste_clipboard_after", 
  "goto_file", 
  "goto_last_modification", 
  "goto_last_modified_file",
  ":buffer-close!"
]

[keys.insert]
j = { j = "normal_mode" } # Maps `jk` to exit insert mode
C-c = "normal_mode" # Maps `jk` to exit insert mode
