theme = "kanagawa_transparent"

[editor]
completion-trigger-len = 1
line-number = "relative"
bufferline = "multiple"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[keys.normal]
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
# Yank to end of line from cursor
Y = ["select_mode", "goto_line_end", "yank", "normal_mode"]
# Delete to end of line from cursor
D = "kill_to_line_end"
# Buffer management
"C-n" = "goto_next_buffer"
"C-p" = "goto_previous_buffer"
"space" = { "c" = ":buffer-close" }
# Move highlighted lines
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
