theme = "gruv_custom"

[editor]
completion-trigger-len = 1
line-number = "relative"
bufferline = "multiple"
cursorline = true
true-color = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"# Yank to end of line from cursor
Y = ["select_mode", "goto_line_end", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
# Delete to end of line from cursor
D = "kill_to_line_end"
# Buffer management
C-l = "goto_next_buffer"
C-h = "goto_previous_buffer"
space = {  "c" = ":buffer-close" }
# Move highlighted lines
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]   
C-p = ["file_picker"]
C-b = ["buffer_picker"]

[keys.insert]
j = { j = "normal_mode" } # Maps `jk` to exit insert mode
C-c = "normal_mode" # Maps `jk` to exit insert mode

# command list here: https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs