[[language]]
name = "twig"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "twig"
source = { git = "https://github.com/gbprod/tree-sitter-twig", rev = "807b293fec3fead64f54c64fdf6fb05516c032b9" }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "php"
source = { git = "https://github.com/tree-sitter/tree-sitter-php", rev = "f860e598194f4a71747f91789bf536b393ad4a56" }

[[language]]
name = "javascript"
formatter = { command = "prettier" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "tsx"
formatter = { command = "prettier" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "jsx"
formatter = { command = "prettier" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "go"
formatter = { command = "gofmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "rust"
config.check.command = "clippy"