#!/bin/bash

# Get the list of available audio sinks
HEADPHONES=$(pactl list short sinks | grep -i 'analog' | awk '{print $1}')
SPEAKERS=$(pactl list short sinks | grep -i 'hdmi' | awk '{print $1}')

# Use dmenu to select between headphones and speakers
SELECTED_OUTPUT=$(echo -e "Headphones\nSpeakers" | dmenu -fn 'Ubuntu Sans Regular-13' -i -p "Select Audio Output:")

# Set the selected output
if [ "$SELECTED_OUTPUT" == "Headphones" ]; then
    pactl set-default-sink "$HEADPHONES"
    notify-send -h string:bgcolor:#bf616a "Audio switched to headphones!"
elif [ "$SELECTED_OUTPUT" == "Speakers" ]; then
    pactl set-default-sink "$SPEAKERS"
    notify-send -h string:bgcolor:#a3be8c "Audio switched to speakers!"
else
    notify-send -h string:bgcolor:#d08770 "No valid output selected!"
fi
