#!/usr/bin/env bash

# dmenu theming
lines="-l 20"
font="-fn Ubuntu Sans Regular-13"
colors=" "

selected="$(ps -a -u $USER | \
            dmenu -i -p "Type to search and select process to kill" -l 5 -fn 'Ubuntu Sans Regular-13'
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -i -p "$selected will be killed, are you sure?" -l 5 -fn 'Ubuntu Sans Regular-13'
            )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
