#!/bin/bash

# Prompt the user to select an area for the screenshot using maim
echo "Select the area for the screenshot. Press Enter when done."
maim -s /tmp/screenshot.png

# Check if the screenshot was taken
if [ $? -eq 0 ]; then
    # Copy the screenshot to the clipboard using xclip
    xclip -selection clipboard -t image/png < /tmp/screenshot.png
    echo "Screenshot taken and copied to clipboard."
else
    echo "Screenshot was not taken."
fi
