#!/bin/bash

# Options for shutdown, restart, or sleep
OPTIONS="Shutdown\nSleep\nRestart"

# Use dmenu to select an option
SELECTED_ACTION=$(echo -e "$OPTIONS" | dmenu -i -p "Select Action:" -fn 'Ubuntu Sans Regular-13' -l 3)

# Perform the selected action
case "$SELECTED_ACTION" in
    "Shutdown")
		notify-send -i system-shutdown "System shutting down..."
        sudo halt
        ;;
    "Sleep")
		notify-send -i system-log-out "System going to sleep..."
       	sudo zzz -H 
        ;;
    "Restart")
		notify-send -i system-reboot "System restarting.."
        sudo reboot
        ;;
esac
