#!/bin/bash

# Define available options
OPTIONS="Chrome\nYouTube\nSpotify\nChatGpt"

# Prompt for search query or select from options using dmenu
SELECTED=$(echo -e "$OPTIONS" | dmenu -i -p "Query:" -fn 'Ubuntu Sans Regular-13' -l 5)

# If a selection is made, handle it
case "$SELECTED" in
    "Browser")
        vivaldi-stable 
        ;;
    "YouTube")
        vivaldi-stable "https://www.youtube.com"
        ;;
    "Spotify")
        vivaldi-stable "https://www.spotify.com"
        ;;
    "ChatGpt")
        vivaldi-stable "https://chatgpt.com/"
        ;;
    *)
	# If not a valid option, perform a Google search with the entered query
	if [ -n "$SELECTED" ]; then
		vivaldi-stable "https://www.google.com/search?q=$(echo "$SELECTED" | sed 's/ /+/g')"
	fi
	;;
esac
