#!/bin/bash

# Define available options
OPTIONS="Chrome\nYouTube\nChatGpt"

# Prompt for search query or select from options using dmenu
SELECTED=$(echo -e "$OPTIONS" | dmenu -i -p "Query:" -fn 'Ubuntu Sans Regular-13' -l 3)

# If a selection is made, handle it
case "$SELECTED" in
    "Chrome")
        chromium 
        ;;
    "YouTube")
        chromium "https://www.youtube.com"
        ;;
    "ChatGpt")
        chromium "https://chatgpt.com/"
        ;;
    *)
	# If not a valid option, perform a Google search with the entered query
	if [ -n "$SELECTED" ]; then
		chromium "https://www.google.com/search?q=$(echo "$SELECTED" | sed 's/ /+/g')"
	fi
	;;
esac
