notify=false
library_tabs = [ "tracks", "podcasts", "playlists", "browse" ]

[theme]
background = "default"
primary = '#e8e8d3'
secondary = '#4e4e43'
title = '#99ad6a'
playing = '#e1b700'
playing_selected = '#e1b700'
highlight = '#000000'
highlight_bg = '#8b8b8b'
error = '#f0a0c0'
error_bg = '#cf6a4c'
statusbar = '#99ad6a'
statusbar_progress = '#99ad6a'
search_match = '#8197bf'

[keybindings]
"1" = "focus queue"
"2" = "focus library"
"3" = "focus search"
"p" = "playpause"
"q" = "noop"
"Shift+q" = "quit"

